const i18Obj = {
  'ENG': {
    'cv': 'CV',
    'links': 'Links',
    'news': 'News',
    'translations': 'Translations',
    'contacts': 'Contacts',
    'image-sign': 'Vicente da Silva, one of the last Guató speakers, and I at Vicente\'s residence, July 2019',
    'hero-title': 'Kristina Balykova',
    'hero-about-main': 'I am a Ph.D. student in the Linguistics Department of the University of Texas at Austin. Since 2017, I have been doing linguistic fieldwork with two endangered languages spoken in Brazil, Wa\'ikhana (East Tukano) and Guató (isolate). My Ph.D. project aims at describing Guató morphosyntax.',
    'hero-about-additionally': 'I was born in Yoshkar-Ola, Russia. In 2011, I moved to Brazil.',
    'download': 'Download',
    'show-cv': 'Show CV',
    'translation-1': 'Desenhos corporais dos índios Kadiweu (Brasil)',
    'translation-2': 'Os Guató e a sua região',
  },
  'POR': {
    'cv': 'CV',
    'links': 'Links',
    'news': 'Notícias',
    'translations': 'Traduções',
    'contacts': 'Contatos',
    'image-sign': 'Vicente da Silva, one of the last Guató speakers, and I at Vicente\'s residence, July 2019',
    'hero-title': 'Kristina Balykova',
    'hero-about-main': 'I am a Ph.D. student in the Linguistics Department of the University of Texas at Austin. Since 2017, I have been doing linguistic fieldwork with two endangered languages spoken in Brazil, Wa\'ikhana (East Tukano) and Guató (isolate). My Ph.D. project aims at describing Guató morphosyntax.',
    'hero-about-additionally': 'I was born in Yoshkar-Ola, Russia. In 2011, I moved to Brazil.',
    'download': 'Download',
    'show-cv': 'Mostrar currículo',
    'translation-1': 'Desenhos corporais dos índios Kadiweu (Brasil)',
    'translation-2': 'Os Guató e a sua região',
  },
  'RUS': {
    'cv': 'Резюме',
    'links': 'Ссылки',
    'news': 'Новости',
    'translations': 'Переводы',
    'contacts': 'Контакты',
    'image-sign': 'Vicente da Silva, one of the last Guató speakers, and I at Vicente\'s residence, July 2019',
    'hero-title': 'Kristina Balykova',
    'hero-about-main': 'I am a Ph.D. student in the Linguistics Department of the University of Texas at Austin. Since 2017, I have been doing linguistic fieldwork with two endangered languages spoken in Brazil, Wa\'ikhana (East Tukano) and Guató (isolate). My Ph.D. project aims at describing Guató morphosyntax.',
    'hero-about-additionally': 'I was born in Yoshkar-Ola, Russia. In 2011, I moved to Brazil.',
    'download': 'Загрузить',
    'show-cv': 'Показать резюме',
    'translation-1': 'Desenhos corporais dos índios Kadiweu (Brasil)',
    'translation-2': 'Os Guató e a sua região',
  }
}
export default i18Obj;
