const i18Obj = {
  'ENG': {
    'cv': 'CV',
    'links': 'Links',
    'news': 'News',
    'translations': 'Translations',
    'contacts': 'Contacts',
    'image-sign': 'Vicente da Silva, one of the last Guató speakers, and I at Vicente\'s residence, July 2019',
    'hero-title': 'Kristina Balykova',
    'hero-about-main': 'I am a Ph.D. student in the Linguistics Department of the University of Texas at Austin. Since 2017, I have been doing linguistic fieldwork with two endangered languages spoken in Brazil, Wa\'ikhana (East Tukano) and Guató (isolate). My Ph.D. project aims at describing Guató morphosyntax.',
    'hero-about-additionally': 'I was born in Yoshkar-Ola, Russia. In 2011, I moved to Brazil.',
    'download': 'Download',
    'show-cv': 'Show CV',
  },
  'POR': {
    'cv': 'CV',
    'links': 'Links',
    'news': 'Notícias',
    'translations': 'Traduções',
    'contacts': 'Contatos',
    'image-sign': 'Vicente da Silva, um dos últimos falantes de Guató, e eu na residência de Vicente, julho de 2019',
    'hero-title': 'Kristina Balykova',
    'hero-about-main': 'Eu sou um Ph.D. estudante do Departamento de Linguística da Universidade do Texas em Austin. Desde 2017, venho fazendo trabalho de campo linguístico com duas línguas ameaçadas de extinção faladas no Brasil, Wa\'ikhana (East Tukano) e Guató (isolado). Meu Ph.D. projeto visa descrever a morfossintaxe Guató.',
    'hero-about-additionally': 'Nasci em Yoshkar-Ola, Rússia. Em 2011, me mudei para o Brasil.',
    'download': 'Download',
    'show-cv': 'Mostrar currículo',
  },
  'RUS': {
    'cv': 'Резюме',
    'links': 'Ссылки',
    'news': 'Новости',
    'translations': 'Переводы',
    'contacts': 'Контакты',
    'image-sign': 'Висенте да Силва, один из последних носителей Гуато. Висенте, июль 2019г.',
    'hero-title': 'Кристина Балыкова',
    'hero-about-main': 'Я доктор философии и студент факультета лингвистики Техасского университета в Остине. С 2017 года я провожу лингвистические полевые исследования с двумя исчезающими языками, на которых говорят в Бразилии: Ваикхана (восточный тукано) и Гуато (изолированный). Моя докторская дессертация направлена на описание морфосинтаксиса Гуато.',
    'hero-about-additionally': 'Я родилась в г. Йошкар-Ола (Россия). В 2011 году я переехала в Бразилию.',
    'download': 'Загрузить',
    'show-cv': 'Показать резюме',
  }
}
export default i18Obj;
